* Overell
- In morse.cabal (as generated by stack)
-- change address on github
-- change author
-- change maintainer
-- change copyright
** Preamble
*** cabal file from stack has

----
extra-source-files:
    ChangeLog.md
    README.md
source-repository head
  type: git
  location: https://github.com/gptix/haskellbook-morse

----

- [ ] what do these do?
- [ ] should they be removed or edited?

** Stanza - library
*** stack's version does not have the following build-depends:
----
 , containers
, QuickCheck
-----	
- [X] Added them.

*** stack's version of the cabal file has
----
 exposed-modules:
      Lib
----

whereas the version from the book has

----
  exposed-modules:  Morse
----
 
- [ ] Change 'Lib' to 'Morse'?
- [ ] Make related changes in any other files (*.yaml?)

*** stack's version has 
----
  other-modules:
      Paths_morse
----
- [ ] What does this affect?
- [ ] Should I change it?

** executable stanza
*** stack's version
-----
executable morse-exe
-----

whereas in the book the line is

-----
executable morse
-----

- [X] update 'morse.cabal' to match book.

*** stack version has

-----
hs-source-dirs:
      app
-----

whereas book version has

-----
  hs-source-dirs:   src
-----

- [X] Change cabal file to match book version.
*** stack version has

----
 ghc-options: -threaded -rtsopts -with-rtsopts=-N
----

whereas book version has

----
  ghc-options:      -Wall -fwarn-tabs
----

- [X] Change cabal file to match book version.

- [X] Add to 'build-depends'

----
  , containers
  , QuickCheck
---- 

*** stack version has

----
other-modules:
      Paths_morse
----

- [ ] What does this do?



** Stanza morse-test

*** This is named 'morse-test' in the version made by stack, but 'tests' in version in book.
- [ ] If I change this name, do I have to make changes in other files?


*** 'main-is' is 'Spec.hs' in stack version, but 'tests.hs' in book version.
- [ ] If I change this name, do I have to make changes in other files?

*** 'hs-source-dirs' is 'test' in stack vesion, and 'tests' in book version.

- [ ] I probably should change this. If I do, must I make changes to other files?

*** build-depends
- [X] add 
----
 , containers
 , QuickCheck
----
